"""empty message

Revision ID: 1b6b6d44e819
Revises: ff47393a68ea
Create Date: 2022-12-23 20:40:32.318806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6b6d44e819'
down_revision = 'ff47393a68ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tq_place', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_race', schema=None) as batch_op:
        batch_op.drop_column('tq_place')

    # ### end Alembic commands ###
