"""empty message

Revision ID: 55a6d320b385
Revises: 072e72bad563
Create Date: 2022-12-23 18:16:09.832452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a6d320b385'
down_revision = '072e72bad563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hz', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.drop_column('hz')

    # ### end Alembic commands ###
