"""empty message

Revision ID: 98740cace3fc
Revises: 1b6b6d44e819
Create Date: 2022-12-23 20:40:47.795086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98740cace3fc'
down_revision = '1b6b6d44e819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_race', schema=None) as batch_op:
        batch_op.drop_column('tq_place')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tq_place', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
