"""empty message

Revision ID: a85846b50edf
Revises: 55a6d320b385
Create Date: 2022-12-23 19:16:32.843775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85846b50edf'
down_revision = '55a6d320b385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hz', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.drop_column('hz')

    # ### end Alembic commands ###
