SECRET_KEY = 'Renat12345'

SQLALCHEMY_DATABASE_URI = f'postgresql+psycopg2://postgres:1234@db:5432/my_db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True

ADMIN_ROLE_ID = 1
MODERATOR_ROLE_ID = 2
USER_ROLE_ID = 3
