FROM python:3.9.14-alpine3.16
USER root
COPY . .
RUN apk update && pip install --upgrade pip && apk add postgresql-dev gcc g++ python3-dev musl-dev && pip install pytest && pip install -r req.txt
WORKDIR /app
ENTRYPOINT ["python", "-m", "pytest"]
